name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          [
            "3.6.7",
            "3.6.8",
            "3.6.9",
            "3.6.10",
            "3.6.11",
            "3.6.12",
            "3.6.13",
            "3.6.14",
            "3.6.15",
            "3.7.0",
            "3.7.1",
            "3.7.2",
            "3.7.3",
            "3.7.4",
            "3.7.5",
            "3.7.6",
            "3.7.7",
            "3.7.8",
            "3.7.9",
            "3.7.10",
            "3.7.11",
            "3.7.12",
            "3.7.13",
            "3.8.0",
            "3.8.1",
            "3.8.2",
            "3.8.3",
            "3.8.4",
            "3.8.5",
            "3.8.6",
            "3.8.7",
            "3.8.8",
            "3.8.9",
            "3.8.10",
            "3.8.11",
            "3.8.12",
            "3.8.13",
            "3.9.0",
            "3.9.1",
            "3.9.2",
            "3.9.3",
            "3.9.4",
            "3.9.5",
            "3.9.6",
            "3.9.7",
            "3.9.8",
            "3.9.9",
            "3.9.10",
            "3.9.11",
            "3.9.12",
            "3.9.13",
            "3.10.0",
            "3.10.1",
            "3.10.2",
            "3.10.3",
            "3.10.4",
            "3.10.5",
            "3.10.6",
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools
          pip install -e .
      - name: Hello World
        run: |
          python test/hello.py
