name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          [
            "3.8.0",
            "3.8.1",
            "3.8.2",
            "3.8.3",
            "3.8.4",
            "3.8.5",
            "3.8.6",
            "3.8.7",
            "3.8.8",
            "3.8.9",
            "3.8.10",
            "3.8.11",
            "3.8.12",
            "3.8.13",
            "3.9.0",
            "3.9.1",
            "3.9.2",
            "3.9.3",
            "3.9.4",
            "3.9.5",
            "3.9.6",
            "3.9.7",
            "3.9.8",
            "3.9.9",
            "3.9.10",
            "3.9.11",
            "3.9.12",
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools
          pip install -e .
      - name: Hello World
        run: |
          python test/hello.py
